// ADR-0077 (R76 T1 / D-002): closeout-coverage leg — fixture-level red/green
// contract for ship-gate step 1g leg-b. Completion signal = a Grill Round N row
// in docs/adr/index.md (registration means complete). Assertions: (a) registered
// N>=floor without a closeout is red; (b) index<->.scratch drift either way is
// red; (c) empty/unparseable derivation is red; the newest dir in flight prints
// an explicit exemption instead of the old silent fallback (R70 F1).
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { CLOSEOUT_COVERAGE_FLOOR, isCloseoutName, parseRegisteredRounds, scanRoundDirs, assessCloseoutCoverage } from "../../../scripts/closeout-coverage.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..", "..", "..");

let passed = 0, failed = 0;
function assert(cond, msg) { if (!cond) { failed++; console.error("FAIL: " + msg); return; } passed++; }

assert(CLOSEOUT_COVERAGE_FLOOR === 76, "floor is the rule birthday (76)");

// --- isCloseoutName ----------------------------------------------------------
assert(isCloseoutName("round-76-closeout.md"), "closeout filename recognized");
assert(!isCloseoutName("next-round.md"), "next-round task book is not a closeout");
assert(!isCloseoutName("round-76-audit.md"), "audit doc is not a closeout");
assert(!isCloseoutName("round-69-direction.md"), "direction doc is not a closeout (R69 T0)");
// Rework F-2: "closure"-suffixed docs must NOT count — the live counterexample
// was .scratch/grill-round-63/handoffs/2026-09-16-release-closure.md, a release
// record masquerading as a round closeout (the silent-mask shape this leg bans).
assert(!isCloseoutName("2026-09-16-release-closure.md"), "release-closure is not a round closeout (F-2 regression)");
assert(!isCloseoutName("2026-09-13-round58-closure-handoff.md"), "closure-handoff is not a round closeout");
assert(!isCloseoutName("round-57-closure-audit-handoff.md"), "closure-audit-handoff is not a round closeout");
assert(!isCloseoutName("disclosure.md"), "disclosure contains 'closure' only — not a closeout");
assert(!isCloseoutName("enclosure.md"), "enclosure contains 'closure' only — not a closeout");
assert(!isCloseoutName("round-77-closure.md"), "closure (not closeout) is off-convention — fail closed");
assert(!isCloseoutName("round-66-audit-closeout.md"), "audit closeout doc stays excluded by the audit rule");
assert(isCloseoutName("round-77-closeout.md"), "convention-shaped closeout still recognized");

// --- parseRegisteredRounds on the real index ----------------------------------
const realIndex = fs.readFileSync(path.join(root, "docs", "adr", "index.md"), "utf8");
const real = parseRegisteredRounds(realIndex);
assert(real.problems.length === 0, "real docs/adr/index.md parses clean (got: " + real.problems.join("; ") + ")");
assert(real.rounds.has(75) && real.rounds.has(76) && real.rounds.size > 60, "real index yields the known round set (75 + 76 registered)");

// --- parser fail-loud shapes ---------------------------------------------------
const mini = ["hdr",
  "<!-- BEGIN ADR-INDEX (generated by scripts/gen-adr-index.mjs — do not edit by hand) -->",
  "The complete numbered record lives in `docs/adr/` — ADR-0001 through ADR-0002.", "",
  "| ADR | Title |", "|-----|-------|",
  "| [0001](0001-x.md) | Something |",
  "| [0002](0002-architecture-grill-round-76-y.md) | Grill Round 76 — Y |",
  "<!-- END ADR-INDEX -->", "tail"].join("\n");
const ok = parseRegisteredRounds(mini);
assert(ok.problems.length === 0 && ok.rounds.has(76) && ok.rounds.size === 1, "mini index parses round 76 (non-round row contributes nothing)");
assert(parseRegisteredRounds(mini.replace("| [0001]", "| BAD-ROW |")).problems.some((e) => e.includes("unparseable line")), "malformed row fails loud");
assert(parseRegisteredRounds(mini.replace("Grill Round 76 — Y", "Grill Round 75 — Y")).problems.some((e) => e.includes("conflicting round")), "file/title round conflict fails loud");
assert(parseRegisteredRounds(mini.replace("grill-round-76-y", "grill-round-076-y")).problems.length === 0, "leading-zero round number is a numeric-equal, not a conflict (F-5③)");
assert(parseRegisteredRounds(mini + "\n| [0099](0099-architecture-grill-round-76-dup.md) | Grill Round 76 dup |\n").problems.length === 0, "row after END marker is out of block scope");
const dup = mini.replace("<!-- END ADR-INDEX -->", "| [0099](0099-architecture-grill-round-76-dup.md) | Grill Round 76 dup |\n<!-- END ADR-INDEX -->");
assert(parseRegisteredRounds(dup).problems.some((e) => e.includes("twice")), "duplicate round registration fails loud");
assert(parseRegisteredRounds("no markers here").problems.some((e) => e.includes("markers")), "missing markers fail loud");

// --- assessCloseoutCoverage fixtures -------------------------------------------
const D = (n, hasCloseout) => ({ name: "grill-round-" + n, n, hasCloseout, closeouts: hasCloseout ? ["round-" + n + "-closeout.md"] : [] });
const IDX = (rounds) => ["<!-- BEGIN ADR-INDEX (generated by scripts/gen-adr-index.mjs — do not edit by hand) -->",
  "The complete numbered record lives in `docs/adr/`.", "", "| ADR | Title |", "|-----|-------|",
  ...rounds.map((n) => "| [0" + n + "](0" + n + "-architecture-grill-round-" + n + "-x.md) | Grill Round " + n + " — X |"),
  "<!-- END ADR-INDEX -->"].join("\n");

// green: registered round with closeout on disk, counts printed
let cov = assessCloseoutCoverage({ dirs: [D(76, true)], indexText: IDX([76]) });
assert(cov.problems.length === 0 && cov.awaiting === null && cov.registeredCount === 1 && cov.completedCount === 1, "registered+closeout is green with coverage counts");

// in-flight exemption: newest dir unregistered, no closeout
cov = assessCloseoutCoverage({ dirs: [D(75, true), D(76, false)], indexText: IDX([75]) });
assert(cov.problems.length === 0 && cov.awaiting === 76, "latest unregistered dir is the explicit exemption");

// red (a): registered but no closeout on disk
cov = assessCloseoutCoverage({ dirs: [D(76, false)], indexText: IDX([76]) });
assert(cov.problems.some((e) => e.includes("round 76") && e.includes("no closeout doc")), "assertion (a): registered-without-closeout is red");

// red (b) forward: closeout on disk but no registration
cov = assessCloseoutCoverage({ dirs: [D(76, true)], indexText: IDX([75]) });
assert(cov.problems.some((e) => e.includes("closeout doc(s) on disk but no Grill Round 76")), "assertion (b): closeout-without-registration is red");

// red (b) reverse: registered but the dir is gone entirely
cov = assessCloseoutCoverage({ dirs: [], indexText: IDX([76]) });
assert(cov.problems.some((e) => e.includes("round 76") && e.includes("does not exist")), "assertion (b): registered-but-dir-missing is red");

// red (b) stale in-flight: a non-latest unregistered dir without closeout is drift
cov = assessCloseoutCoverage({ dirs: [D(76, false), D(77, false)], indexText: IDX([75]) });
assert(cov.awaiting === 77 && cov.problems.some((e) => e.includes("round 76") && e.includes("neither registered nor the in-flight latest")), "non-latest unregistered dir is drift, not exemption");

// red (c): empty derivation
cov = assessCloseoutCoverage({ dirs: [D(76, true)], indexText: IDX([]) });
assert(cov.problems.some((e) => e.includes("zero Grill Round registrations")), "assertion (c): empty derivation is red");

// floor grandfathering: pre-floor rounds are out of scope in both directions
cov = assessCloseoutCoverage({ dirs: [D(50, false), D(75, true), D(76, false)], indexText: IDX([75]) });
assert(cov.problems.length === 0 && cov.awaiting === 76, "pre-floor dirs never produce violations");

// rework F-4: scoped-empty derivation — nothing registered and no dirs at or
// above floor — is a vacuous green; the leg reds instead of passing silently.
cov = assessCloseoutCoverage({ dirs: [D(75, true)], indexText: IDX([75]) });
assert(cov.problems.some((e) => e.includes("nothing to check")), "scoped-empty derivation is red (F-4: no vacuous green)");

// --- scanRoundDirs against a fixture tree --------------------------------------
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "r76-cov-"));
try {
  fs.mkdirSync(path.join(tmp, "grill-round-75", "handoffs"), { recursive: true });
  fs.mkdirSync(path.join(tmp, "grill-round-76", "handoffs"), { recursive: true });
  fs.mkdirSync(path.join(tmp, "not-a-round", "handoffs"), { recursive: true });
  fs.writeFileSync(path.join(tmp, "grill-round-75", "handoffs", "round-75-closeout.md"), "# x");
  fs.writeFileSync(path.join(tmp, "grill-round-76", "handoffs", "next-round.md"), "# x");
  const dirs = scanRoundDirs(tmp);
  assert(dirs.length === 2 && dirs[0].n === 76 && dirs[1].n === 75, "scanRoundDirs filters non-round dirs and sorts desc");
  assert(dirs[1].hasCloseout && !dirs[0].hasCloseout, "hasCloseout reflects handoffs/ closeout docs only");
} finally { fs.rmSync(tmp, { recursive: true, force: true }); }

// --- the leg is wired into ship-gate (a dropped assertion = a dropped gate) ----
const sg = fs.readFileSync(path.join(root, "scripts", "ship-gate.mjs"), "utf8");
assert(sg.includes("assessCloseoutCoverage") && sg.includes("scanRoundDirs"), "ship-gate wires the coverage module");
assert(sg.includes("awaiting closeout: round "), "ship-gate prints the structured exemption line");
assert(sg.includes("CLOSEOUT_COVERAGE_FLOOR"), "ship-gate reports the floor in the coverage count line");

console.log("closeout-coverage.test: " + passed + " passed, " + failed + " failed");
process.exit(failed === 0 ? 0 : 1);
