// ADR-0012 D14: Routing card shared constants — one source, many outputs.
// Extracted from session-start.ts, cursor.ts, antigravity.ts (debt ledger trigger met: 4 platforms).

import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

export const DEFAULT_ROUTING_CARD = [
  "[anysearch plugin active]",
  "Tools available (ans_* prefix):",
  "- search_web: real-time multi-source web search",
  "- research_web: deep research (minute-level, multi-hop)",
  "- recall_memory: FTS5 research memory recall (time edge effect)",
  "- query_knowledge: enterprise RAG retrieval",
  "- ans_chat: agent loop with retrieval augmentation",
  "",
  "Trigger rules:",
  "- Fresh facts / current events -> search_web",
  "- Complex multi-step research -> research_web",
  "- Recall prior search results -> recall_memory",
  "- Domain-specific knowledge base -> query_knowledge",
  "- Complex multi-tool research -> ans_chat",
  "- Skip redundant search if recall_memory already has relevant results",
  "",
  "Fail-open: if anysearch server is down, tools degrade gracefully (no block).",
  "For detailed guidance: see SKILL.md (anysearch skill).",
].join("\n");

export const MDC_CONTENT = [
  "---",
  "description: anysearch plugin routing card",
  "alwaysApply: true",
  "---",
  "",
  DEFAULT_ROUTING_CARD,
  "",
  "---",
  "This file is auto-generated by anysearch hook.",
  "Do not edit manually. Changes will be overwritten on next hook run.",
  "---",
].join("\n");

// ADR-0012 D14: high-user override via .anysearch/routing-card.json (fail-open).
export function loadRoutingCard(cwd: string): string {
  const overridePath = join(cwd, ".anysearch", "routing-card.json");
  try {
    if (existsSync(overridePath)) {
      const raw = readFileSync(overridePath, "utf8");
      const parsed = JSON.parse(raw);
      if (typeof parsed.routingCard === "string" && parsed.routingCard.length > 0) {
        return parsed.routingCard;
      }
    }
  } catch (e) {
    // Fail-open: JSON parse error -> stderr warning + fallback to default.
    process.stderr.write("[anysearch] routing-card.json parse error: " + (e instanceof Error ? e.message : String(e)) + "\n");
  }
  return DEFAULT_ROUTING_CARD;
}
