// SessionStart hook: inject static routing card at session start.
// ADR-0010 D2: Progressive Disclosure Three-Layer — this is the lightest layer.
// ADR-0011 D2: ~20 lines / 150-400 token routing card, 4 blocks.
// ADR-0011 D5: .mdc dynamically generated by hook at runtime (one source, two outputs).
// ADR-0011 D6: do NOT modify host AGENTS.md, inject via hook/.mdc only.
// Cross-platform: Claude/Codex have SessionStart; Cursor/Antigravity fall back to .mdc.

import { writeFileSync, existsSync, readFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

// ADR-0012 D14: routing card + MDC content imported from shared routing-card.ts module.
import { DEFAULT_ROUTING_CARD as ROUTING_CARD, MDC_CONTENT, loadRoutingCard } from "./routing-card.js";

interface SessionStartStdin {
  // ADR-0066: real hosts inject hook_event_name; event kept as legacy fallback.
  hook_event_name?: string;
  event?: string;
  cwd?: string;
  session_id?: string;
}

// ADR-0011 D5: dynamically generate .mdc rule file at runtime.
// Check if .cursor/rules/anysearch.mdc exists and is up-to-date; write if not.
function ensureMdc(cwd: string): void {
  const rulesDir = join(cwd, ".cursor", "rules");
  const mdcPath = join(rulesDir, "anysearch.mdc");
  try {
    if (existsSync(mdcPath)) {
      const existing = readFileSync(mdcPath, "utf8");
      if (existing === MDC_CONTENT) return; // Up-to-date, skip.
    }
    mkdirSync(rulesDir, { recursive: true });
    writeFileSync(mdcPath, MDC_CONTENT, "utf8");
  } catch {
    // Fail-open: .mdc write failure is non-fatal.
  }
}

async function main(): Promise<void> {
  let input = "";
  for await (const chunk of process.stdin) input += chunk;

  let stdin: SessionStartStdin;
  try { stdin = JSON.parse(input); }
  catch { process.exit(0); }

  // Only handle SessionStart event.
  const event = stdin.hook_event_name ?? stdin.event;
  if (event !== "SessionStart" && event !== "session_start" && event !== "sessionStart") {
    process.exit(0);
  }

  const cwd = stdin.cwd || process.cwd();

  // ADR-0011 D5: generate .mdc rule file for Cursor/Antigravity fallback.
  ensureMdc(cwd);

  // Output routing card as additionalContext for the host agent.
  // Claude format: { additionalContext: "..." }
  // Codex format: { additionalContext: "..." }
  process.stdout.write(JSON.stringify({ additionalContext: ROUTING_CARD }));
  process.exit(0);
}

main();
