// SessionStart hook: inject static routing card at session start.
// ADR-0010 D2: Progressive Disclosure Three-Layer — this is the lightest layer.
// ADR-0011 D2: ~20 lines / 150-400 token routing card, 4 blocks.
// ADR-0011 D5: .mdc dynamically generated by hook at runtime (one source, two outputs).
// ADR-0011 D6: do NOT modify host AGENTS.md, inject via hook/.mdc only.
// Cross-platform: Claude/Codex have SessionStart; Cursor/Antigravity fall back to .mdc.

import { writeFileSync, existsSync, readFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";

// Static routing card — inject at session start, never changes.
const ROUTING_CARD = "[anysearch plugin active]\nTools available (ans_* prefix):\n- search_web: real-time multi-source web search\n- research_web: deep research (minute-level, multi-hop)\n- recall_memory: FTS5 research memory recall (time edge effect)\n- query_knowledge: enterprise RAG retrieval\n- ans_chat: PiAgentRuntime agent loop for complex queries\n\nTrigger rules:\n- Current events / factual lookup -> search_web\n- Multi-step research / synthesis -> research_web\n- Recall prior results from this session -> recall_memory\n- Enterprise knowledge base -> query_knowledge\n- Complex multi-tool research -> ans_chat\n- Skip redundant search if recall_memory already has relevant results\n\nFail-open: if anysearch server is down, tools degrade gracefully (no block).\nFor detailed guidance: see SKILL.md (anysearch skill).";

// .mdc rule file content (Cursor format with frontmatter).
const MDC_CONTENT = "---\ndescription: anysearch plugin routing card\nalwaysApply: true\n---\n\n[anysearch plugin active]\nTools available (ans_* prefix):\n- search_web: real-time multi-source web search\n- research_web: deep research (minute-level, multi-hop)\n- recall_memory: FTS5 research memory recall (time edge effect)\n- query_knowledge: enterprise RAG retrieval\n- ans_chat: PiAgentRuntime agent loop for complex queries\n\nTrigger rules:\n- Current events / factual lookup -> search_web\n- Multi-step research / synthesis -> research_web\n- Recall prior results from this session -> recall_memory\n- Enterprise knowledge base -> query_knowledge\n- Complex multi-tool research -> ans_chat\n- Skip redundant search if recall_memory already has relevant results\n\nFail-open: if anysearch server is down, tools degrade gracefully (no block).\nFor detailed guidance: see SKILL.md (anysearch skill).\n\n---\nThis file is auto-generated by anysearch SessionStart hook.\nDo not edit manually. Changes will be overwritten on next session start.\n---";

interface SessionStartStdin {
  event?: string;
  cwd?: string;
  session_id?: string;
}

// ADR-0011 D5: dynamically generate .mdc rule file at runtime.
// Check if .cursor/rules/anysearch.mdc exists and is up-to-date; write if not.
function ensureMdc(cwd: string): void {
  const rulesDir = join(cwd, ".cursor", "rules");
  const mdcPath = join(rulesDir, "anysearch.mdc");
  try {
    if (existsSync(mdcPath)) {
      const existing = readFileSync(mdcPath, "utf8");
      if (existing === MDC_CONTENT) return; // Up-to-date, skip.
    }
    mkdirSync(rulesDir, { recursive: true });
    writeFileSync(mdcPath, MDC_CONTENT, "utf8");
  } catch {
    // Fail-open: .mdc write failure is non-fatal.
  }
}

async function main(): Promise<void> {
  let input = "";
  for await (const chunk of process.stdin) input += chunk;

  let stdin: SessionStartStdin;
  try { stdin = JSON.parse(input); }
  catch { process.exit(0); }

  // Only handle SessionStart event.
  if (stdin.event !== "SessionStart" && stdin.event !== "session_start" && stdin.event !== "sessionStart") {
    process.exit(0);
  }

  const cwd = stdin.cwd || process.cwd();

  // ADR-0011 D5: generate .mdc rule file for Cursor/Antigravity fallback.
  ensureMdc(cwd);

  // Output routing card as additionalContext for the host agent.
  // Claude format: { additionalContext: "..." }
  // Codex format: { additionalContext: "..." }
  process.stdout.write(JSON.stringify({ additionalContext: ROUTING_CARD }));
  process.exit(0);
}

main();
