// SessionStart hook: inject static routing card at session start.
// ADR-0010 D2: Progressive Disclosure Three-Layer — this is the lightest layer.
// ADR-0011 D2: ~20 lines / 150-400 token routing card, 4 blocks.
// ADR-0011 D5: .mdc dynamically generated by hook at runtime (one source, two outputs).
// ADR-0011 D6: do NOT modify host AGENTS.md, inject via hook/.mdc only.
// Cross-platform: Claude/Codex have SessionStart; Cursor/Antigravity fall back to .mdc.

// ADR-0012 D14: routing card + MDC content imported from shared routing-card.ts module.
import { DEFAULT_ROUTING_CARD as ROUTING_CARD, ensureMdc } from "./routing-card.js";

interface SessionStartStdin {
  // ADR-0066: real hosts inject hook_event_name; event kept as legacy fallback.
  hook_event_name?: string;
  event?: string;
  cwd?: string;
  session_id?: string;
}

async function main(): Promise<void> {
  let input = "";
  for await (const chunk of process.stdin) input += chunk;

  let stdin: SessionStartStdin;
  try { stdin = JSON.parse(input); }
  catch { process.exit(0); }

  // Only handle SessionStart event.
  const event = stdin.hook_event_name ?? stdin.event;
  if (event !== "SessionStart" && event !== "session_start" && event !== "sessionStart") {
    process.exit(0);
  }

  const cwd = stdin.cwd || process.cwd();

  // ADR-0011 D5: generate .mdc rule file for Cursor/Antigravity fallback.
  ensureMdc(cwd, ".cursor");

  // Output routing card as additionalContext for the host agent.
  // Host contract split (R66 F-03 + R67 T1): both Claude Code and Codex require
  // the hookSpecificOutput envelope — Codex drops bare { additionalContext }
  // ~80% of the time on the real host (verified 0.142.5). `--envelope` is
  // passed by the generated Claude and Codex configs. Cursor / Antigravity keep
  // the bare shape and primarily rely on the .mdc fallback written above.
  if (process.argv.includes("--envelope")) {
    process.stdout.write(JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "SessionStart",
        additionalContext: ROUTING_CARD,
      },
    }));
  } else {
    process.stdout.write(JSON.stringify({ additionalContext: ROUTING_CARD }));
  }
  process.exit(0);
}

main();
